### ISSUE TITLE
Floating IP doesn't work on EKS when #nodes > 1

### ISSUE THREAD

**Issue by kiemlicz** [projectcalico/cni-plugin#1027]
## Expected Behavior
When setting floating IP and sending traffic to floating IP I expect it to work like the service does

## Current Behavior
POD IP reachable from other nodes (not hosting the POD)  
Floating IP not reachable from other nodes (not hosting the POD)  

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. Setup Calico on AWS EKS: https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks
2. Setup floating ip feature: https://docs.projectcalico.org/networking/add-floating-ip
3. setup two nodes
4. Create two PODs, one with floating ip, other without, spread them across nodes.  
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: debug
    app: application
  name: application
spec:
  nodeSelector:
    role: a  # switch for other node
  securityContext:
    runAsUser: 0
  containers:
    - image: debian:buster
      name: application
      command:
        - bash
      stdin: true
      tty: true
      securityContext:
        privileged: true
```
5. listen on node with floating ip: `nc ... 0.0.0.0 9999`, send something from other node. Nothing reaches the listening port, using direct POD ip works

## Your Environment
setup like so https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks
* CNI plugin version - latest for today...
* Orchestrator version 1.18 kubernetes from EKS
* Operating System and version: Amazon Linux
