### ISSUE TITLE
Fail to cleanup IP addresses when using "usePodCidr"

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#254]
I noticed that we're not substituting the "subnet: usePodCidr" on DEL when using the host-local IPAM plugin, which means we end up leaking IPs.

```
time="2017-01-30T05:16:05Z" level=error msg="invalid CIDR address: usePodCidr"
```

**Comment by caseydavenport** [comment]
@tomdee I've added this to v2.1.0 since it's pretty important.

**Comment by tomdee** [comment]
From a quick look it seems that host-local does expect the subnet when creating the allocator. Still worth digging into some more to see if a dummy value could be used

**Comment by gunjan5** [comment]
@tomdee It needs the subnet: 
```
root@node-01:/opt/cni/bin# ./host-local < conf5
{
    "code": 100,
    "msg": "missing field \"subnet\" in IPAM configuration"
}
```

I also tried `""` as @caseydavenport suggested, but that doesn't work either:
```
root@node-01:/opt/cni/bin# ./host-local < conf4
{
    "code": 100,
    "msg": "invalid CIDR address: "
}
```

So, I guess we will have to get the CIDR from k8s backend and then pass that in

**Comment by gunjan5** [comment]
ok so I tried `ADD`ing containers with some CIDR and then `DEL` with a dummy CIDR as @caseydavenport suggested, and that seems to work. Here is the result for my own record:
```yaml
root@node-01:/opt/cni/bin# cat conf3
{
    "name": "any_name",
    "type": "calico",
    "kubernetes": {
        "kubeconfig": "/path/to/kubeconfig",
        "node_name": "node-name-in-k8s"
    },
    "ipam": {
        "type": "host-local",
        "subnet": "11.11.0.0/24"
    }
}
root@node-01:/opt/cni/bin#
root@node-01:/opt/cni/bin# cat conf33
{
    "name": "any_name",
    "type": "calico",
    "kubernetes": {
        "kubeconfig": "/path/to/kubeconfig",
        "node_name": "node-name-in-k8s"
    },
    "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/24"   // <------------- DUMMY CIDR
    }
}
```
```bash
root@node-01:/opt/cni/bin# export CNI_CONTAINERID=badbeef888
root@node-01:/opt/cni/bin# ./host-local < conf3
{
    "ip4": {
        "ip": "11.11.0.3/24",
        "gateway": "11.11.0.1"
    },
    "dns": {}
}root@node-01:/opt/cni/bin# export CNI_CONTAINERID=badbeef777
root@node-01:/opt/cni/bin# ./host-local < conf3
{
    "ip4": {
        "ip": "11.11.0.4/24",
        "gateway": "11.11.0.1"
    },
    "dns": {}
}root@node-01:/opt/cni/bin# export CNI_CONTAINERID=badbeef666
root@node-01:/opt/cni/bin# ./host-local < conf3
{
    "ip4": {
        "ip": "11.11.0.5/24",
        "gateway": "11.11.0.1"
    },
    "dns": {}
}root@node-01:/opt/cni/bin# export CNI_CONTAINERID=badbeef777
root@node-01:/opt/cni/bin# export CNI_COMMAND=DEL
root@node-01:/opt/cni/bin# ./host-local < conf33
root@node-01:/opt/cni/bin# export CNI_CONTAINERID=badbeef555
root@node-01:/opt/cni/bin# export CNI_COMMAND=ADD
root@node-01:/opt/cni/bin# ./host-local < conf3
{
    "ip4": {
        "ip": "11.11.0.4/24",
        "gateway": "11.11.0.1"
    },
    "dns": {}
}
```
