### ISSUE TITLE
Pool selection via cni failed when creating pods

### ISSUE THREAD

**Issue by jeffchanjunwei** [projectcalico/cni-plugin#313]
When I test the pool selection function of calico on k8s, it does't work. The config of calico cni and pod  deployment file are showed bellow.
  
 ` calicoctl get ipPool -o yaml `
```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 172.10.0.0/16
  spec:
    ipip:
      enabled: true
      mode: cross-subnet
    nat-outgoing: true
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 192.168.0.0/16
  spec:
    nat-outgoing: true
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: fd80:24e2:f998:72d6::/64
  spec:
    nat-outgoing: true
```

config of cni plugin

```
{
   "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "http://XXXX:2379",
    "log_level": "DEBUG",
    "ipam": {
        "type": "calico-ipam"
        "assign_ipv4": "true",
        "assign_ipv6": "false",
        "ipv4_pools": ["192.168.0.0/16","172.10.0.0/16"],
        "ipv6_pools": ["fd80:24e2:f998:72d6::/64"]
    },
    "policy": {
        "type": "k8s",
        "k8s_api_root": "http://XXXX:8080"
    }
}
```

`kubectl create -f  deployment.yaml`

deployment.yaml 
...
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"172.10.0.0/16\"]"
...
      
But the pod can not be created successfully. Infor is 
FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "centos-4-2354226972-s0m7c_default" with SetupNetworkError: "Failed to setup network for pod \"centos-4-2354226972-s0m7c_default(d1689728-2570-11e7-9687-005056943399)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

How can I fix it ? I also test if I delete   
```
         "assign_ipv4": "true",  "assign_ipv6": "false",
        "ipv4_pools": ["192.168.0.0/16","172.10.0.0/16"],
        "ipv6_pools": ["fd80:24e2:f998:72d6::/64"]
```
and create without annotations it succeed.
**versions:**
    k8s v1.5.1
    calicoctl v1.1.0
    calico/node v1.1.0
    cni plugin-
    calico v 1.6.1
    calico-ipam v1.6.1
    loopback v 0.3.0
