### ISSUE TITLE
Calico CNI can't be used as K8s TPR network object with Multus CNI

### ISSUE THREAD

**Issue by nokia-t1zhou** [projectcalico/cni-plugin#460]
## Expected Behavior

I want to use Calico CNI with Multus CNI, i have create K8s TPR based network object for Calico CNI, and deploy the wanted POD to use this network object, but it's failed. the CNI config detail please see "Steps to Reproduce" part. so could you help me and give the comments for what's wrong in our K8s network object configuration and CNI configuration.
thank you very much!

**i have test the Calico CNI by standalone mode(not working with Multus) , it's working in my env. The CNI config file is as below:**
```
{
    "name": "k8s-calico-network",
    "type": "calico",
    "bridge": "docker0",
    "etcd_endpoints": "https://10.106.243.232:2379,https://10.106.243.251:2379,https://10.106.243.254:2379",
    "etcd_key_file": "/etc/etcd/ssl/etcd-key.pem",
    "etcd_cert_file": "/etc/etcd/ssl/etcd.pem",
    "etcd_ca_cert_file": "/etc/kubernetes/ssl/ca.pem",
    "log_level": "warn",
    "ipam": {
        "type": "calico-ipam"
    },
    "kubernetes": {
        "kubeconfig": "/root/.kube/config"
    }
}
```

**i'm also test it as Multus default network mode, it's working also, the CNI config file is as below:**

```
{
    "name": "my-cni-network",
    "bridge": "docker0",
    "type": "multus",
    "kubeconfig": "/root/.kube/config",
    "delegates": [
       {
             "etcd_endpoints": "https://10.106.243.232:2379,https://10.106.243.251:2379,https://10.106.243.254:2379",
             "etcd_key_file": "/etc/etcd/ssl/etcd-key.pem",
             "etcd_cert_file": "/etc/etcd/ssl/etcd.pem",
             "etcd_ca_cert_file": "/etc/kubernetes/ssl/ca.pem",
             "log_level": "debug",
             "masterplugin": true,
             "name": "my-calico"
             "ipam": {
                 "type": "calico-ipam"
             },
             "kubernetes": {
                 "kubeconfig": "/root/.kube/config"
             }
       }
    ]
}
```
## Steps to Reproduce (for bugs)

1. create K8s TPR
```
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: network.kubernetes.com
description: "A specification of a Network obj in the kubernetes"
versions:
  - name: v1
```
2. create Calico TPR network object
```
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: calico-networkobj
plugin: calico
args: '[
         {
             "etcd_endpoints": "https://10.106.243.232:2379,https://10.106.243.251:2379,https://10.106.243.254:2379",
             "etcd_key_file": "/etc/etcd/ssl/etcd-key.pem",
             "etcd_cert_file": "/etc/etcd/ssl/etcd.pem",
             "etcd_ca_cert_file": "/etc/kubernetes/ssl/ca.pem",
             "log_level": "debug",
             "ipam": {
                 "type": "calico-ipam"
             },
             "kubernetes": {
                 "kubeconfig": "/root/.kube/config"
             }
         }
]'
```
3. after step2, the network object is created
```
root@distro:~/yaml/TPR$ kubectl get network
NAME                      KIND
calico-networkobj         Network.v1.kubernetes.com
ipvlan-10-106-243-192-1   Network.v1.kubernetes.com
ipvlan-10-106-243-192-2   Network.v1.kubernetes.com
ipvlan-eth3-10-5-5-0      Network.v1.kubernetes.com
```
```
root@distro:~/yaml/TPR$ kubectl get network calico-networkobj -o yaml
apiVersion: kubernetes.com/v1
args: '[ { "etcd_endpoints": "https://10.106.243.232:2379,https://10.106.243.251:2379,https://10.106.243.254:2379",
  "etcd_key_file": "/etc/etcd/ssl/etcd-key.pem", "etcd_cert_file": "/etc/etcd/ssl/etcd.pem",
  "etcd_ca_cert_file": "/etc/kubernetes/ssl/ca.pem", "log_level": "debug", "ipam":
  { "type": "calico-ipam" }, "kubernetes": { "kubeconfig": "/root/.kube/config" }
  } ]'
kind: Network
metadata:
  creationTimestamp: 2018-01-26T02:19:07Z
  name: calico-networkobj
  namespace: default
  resourceVersion: "1736688"
  selfLink: /apis/kubernetes.com/v1/namespaces/default/networks/calico-networkobj
  uid: 496927cb-023f-11e8-9216-fa163e81a07e
plugin: calico
```
4. in K8s node, the Multus CNI config file is as below:
```
root@distro:/etc/cni/net.d$ cat 00-multus-network-object.conf 
{
    "name": "my-cni-network",
    "type": "multus",
    "kubeconfig": "/root/.kube/config"
}
```
5. try to deploy POD with Calico network, but it's failed, below is the yaml file:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bfd-calico
  labels:
    app: rcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rcp-bfd
  template:
    metadata:
      labels:
        app: rcp-bfd
      annotations:
        networks: '[
          { "name":"calico-networkobj"}
        ]'  
    spec:
      restartPolicy: Always
      nodeSelector:
        zone: rcp-vm-1
      containers:
      - name: bfd-calico
        image: bfd-test:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        command: ["/bin/bash"]
        args: ["-c","/opt/nokia/bin/bfddaemon 127.0.0.1 49185 '&'"] 
        stdin: true
        tty: true
```
6. the deployment is failed, and the return error is as below:
```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  42s           42s             1       kubelet, 10.106.243.251                 Warning         FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "bfd-calico-4132523957-485jv_default(b79266f0-0240-11e8-9216-fa163e81a07e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"bfd-calico-4132523957-485jv_default(b79266f0-0240-11e8-9216-fa163e81a07e)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"bfd-calico-4132523957-485jv_default\" network: Multus: error in invoke Delegate add - \"calico\": invalid characters detected in the given network name. Only letters a-z, numbers 0-9, and symbols _.- are supported"
```

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):  v2.0.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.12", GitCommit:"87cf3a252e2492a614f1e7c9b1bcd7c6bc0209df", GitTreeState:"clean", BuildDate:"2017-10-25T17:56:41Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.12", GitCommit:"87cf3a252e2492a614f1e7c9b1bcd7c6bc0209df", GitTreeState:"clean", BuildDate:"2017-10-25T17:46:28Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
* CNI config:
* Operating System and version:
* Link to your project (optional):
