### ISSUE TITLE
ARP entries for Pods unstable (switch to unknown and back)

### ISSUE THREAD

**Issue by christianhuening** [projectcalico/cni-plugin#471]
## Expected Behavior

ARP entries stay stable for deployed Pods.

## Current Behavior

I found to have an issue with downloads stalling within a Pod (used by Gitlab Runner to execute builds). They usually start at normal download speeds and then stall after 30 - 60%. A look at the ARP table on the node of the Pod shows me that the Pod Address suddenly lacks an ARP entry (flaps to <unknown>). Then after a (longer) while, the ARP entry suddenly returns for some seconds, the download resumes, then ARP is gone again.

## Steps to Reproduce (for bugs)

1. Deploy Pod that performs download on node with below config

## Context

Builds run in Pods which are downloading lots of things (like JDK, NPM, APT, APK packages etc) or are building docker images, take very long or will fail due to timeouts etc.

![2018-02-12 14 10 04](https://user-images.githubusercontent.com/738953/36099689-d2aacd3a-1003-11e8-997f-d30887634030.jpg)
<img width="751" alt="unknown" src="https://user-images.githubusercontent.com/738953/36099700-da7d1248-1003-11e8-91e4-14a7ed0d0613.png">

## Your Environment

* K8s: 1.9.3
* Flannel: 0.9.1
* Calico Node: 2.6.7
* Calico CNI: 1.11.2
* CNI version: 0.3.0
* OS: Container Linux by CoreOS 1632.2.1 (Ladybug)   4.14.16-coreos
* CNI config:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: canal-config
  namespace: kube-system
data:
  # The interface used by canal for host <-> host communication.
  # If left blank, then the interface is chosen using the node's
  # default route.
  canal_iface: ""

  # Whether or not to masquerade traffic to destinations not within
  # the pod network.
  masquerade: "true"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.3.0",
        "plugins": [
            {
                "type": "calico",
                "log_level": "info",
                "datastore_type": "kubernetes",
                "nodename": "__KUBERNETES_NODE_NAME__",
                "ipam": {
                    "type": "host-local",
                    "subnet": "usePodCidr"
                },
                "policy": {
                    "type": "k8s",
                    "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
                },
                "kubernetes": {
                    "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                    "kubeconfig": "__KUBECONFIG_FILEPATH__"
                }
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true},
                "snat": true
            }
        ]
    }

  # Flannel network configuration. Mounted into the flannel container.
  net-conf.json: |
    {
      "Network": "10.200.0.0/16",
      "Backend": {
        "Type": "vxlan",
        "Port": 4789
      }
    }
```
