### ISSUE TITLE
I want to use service in pod to connect   Externel Mysql but  not use

### ISSUE THREAD

**Issue by Rogary** [projectcalico/cni-plugin#659]
Hello ,I want to use service in pod to connect   Externel Mysql but  not use

in kubernetes  i want to use service and endpoint  to connect a externel mysql like this 
```yml
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-endpoint
  namespace: default
subsets:
  - addresses:
      - ip: 10.111.121.2 # this is externel mysql ip address
    ports:
      - port: 3306
---------
apiVersion: v1
kind: Service
metadata:
  name: mysql-endpoint
  namespace: default
spec:
  ports:
    - port: 3306
```

now i have a Service like this 
```
Name:              mysql-endpoint
Namespace:         default
Labels:            <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mysql-endpoint","namespace":"default","selfLink":"/api/v1/namespa...
Selector:          <none>
Type:              ClusterIP
IP:                10.99.53.23
Port:              <unset>  3306/TCP
TargetPort:        3306/TCP
Endpoints:         10.111.121.2:3306
Session Affinity:  None
```

## Expected Behavior 
In hope that i can use clusterIp + port to connect Externel mysql  in pod 

## Current Behavior 
in  cluster  node  i can telnet  clusterIp port  this Service ,
```
# telnet 10.99.53.23 3306
Trying 10.99.53.23...
Connected to 10.99.53.23.
Escape character is '^]'.
```
but in pod i can't  ,
```
# nc -vzw 10 10.99.53.23 3306
nc: 10.99.53.23 (10.99.53.23:3306): Operation timed out
```
## Possible Solution
i try to modify NetworkPolicy  allow-all 
```
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress
EOF
------------------
kubectl create -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-1
spec:
  podSelector: {}
  ingress:
  - {}
EOF
```
but not use 
then 
i use tcpdump  in mysql node  i got this 
```
15:59:33.043557 IP 192.1.1.24.36009 > nsxjapptst01.cs1cloud.internal.mysql: Flags [S], seq 2624077831, win 28000, options [mss 1400,sackOK,TS val 1060556222 ecr 0,nop,wscale 7], length 0
15:59:33.043614 IP nsxjapptst01.cs1cloud.internal.mysql > 192.1.1.24.36009: Flags [S.], seq 195091831, ack 2624077832, win 28960, options [mss 1460,sackOK,TS val 1061852098 ecr 1060556222,nop,wscale 7], length 0
```
and tcpdump in pod node 
```
16:35:13.452727 IP 192.1.1.24.42053 > nsxjapptst01.cs1cloud.internal.mysql: Flags [S], seq 2971838493, win 28000, options [mss 1400,sackOK,TS val 1062696641 ecr 0,nop,wscale 7], length 0
16:35:14.455413 IP 192.1.1.24.42053 > nsxjapptst01.cs1cloud.internal.mysql: Flags [S], seq 2971838493, win 28000, options [mss 1400,sackOK,TS val 1062697644 ecr 0,nop,wscale 7], length 0
```
**Package has Already arrived to mysql node ,but   NO Package Return** 

192.1.1.24  this is my pod IP but mysql node has no route to 192.1.0.0/16  so package can't return 

so i configed calico ip pool 
like this 
https://docs.projectcalico.org/master/usage/external-connectivity
```
cat << EOF | calicoctl apply -f -
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    cidr: 192.168.0.0/16
    ipipMode: Always
    natOutgoing: true
EOF
```
but it still not work  
in mysql node tcpdump not change

How can i Connect mysql in pod?
