### ISSUE TITLE
ClusterInformation.datastoreReady stays false for k8s cluster with host-local ipam after node reboot 

### ISSUE THREAD

**Issue by jzhoucliqr** [projectcalico/cni-plugin#990]
With latest v3.17 release, for k8s cluster with `host-local` ipam-type, after reboot, the ClusterInformation.datastoreReady stays false never turns to true.

I think it might be caused by https://github.com/projectcalico/cni-plugin/pull/968/files, where below condition is not met. 
```
calicoDS.Status.UpdatedNumberScheduled == calicoDS.Status.DesiredNumberScheduled-calicoDS.Spec.UpdateStrategy.RollingUpdate.MaxUnavailable.IntVal
``` 

For a single node cluster case,  all 3 numbers are 1. Same happens to multi-node clusters. 

```
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 1
    updatedNumberScheduled: 1
```

## Steps to Reproduce (for bugs)

1. setup a single node cluster with host-local ipam type
2. reboot the node
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.17.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):
